version: "3.8"

services:
  db:
    image: postgres:13
    container_name: myapp_db
    environment:
      POSTGRES_DB: devop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sain
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myapp_network

  backend:
    build:
      context: ./Backend
    container_name: myapp_backend
    environment:
      - DATABASE_URL=postgres://postgres:sain@db:5432/devop
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - myapp_network

  frontend:
    build:
      context: ./frontend
    container_name: myapp_frontend
    ports:      
    - "3000:3000"
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
