# Use the official Python image from the Docker Hub
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY . .

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
